name: Semgrep Security Scan

on: [push, pull_request]

jobs:
  semgrep-scan:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (if app is Python)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep Scan
        run: |
          semgrep --config auto --json > semgrep-results.json || true

      - name: Fail if critical issues found
        run: |
          python .github/scripts/evaluate_semgrep.py

      - name: Notify on MS Teams (if critical found)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"text": " Semgrep found critical vulnerabilities in the latest push. Check GitHub Actions for details."}' \
          https://deloitte.webhook.office.com/webhookb2/41f8d5cb-3f09-43df-b095-223831bd83d1@36da45f1-dd2c-4d1f-af13-5abe46b99921/IncomingWebhook/081b06e8bc654a6baeb3ff763dc155e4/d1aa53ae-aa07-4b53-9eb3-dc01af5ac40c/V2jTlqRyUsoSvHMRT2Lhl9J1BPOYz41snXDnr5mzJ5ck01